name = "SlurmAddAllocatedProcs"
uuid = "4b0af0f2-a3e4-42c8-afa2-c5af2ee86004"
authors = ["Jishnu Bhattacharya <jishnub@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
ClusterManagers = "34f1f09b-3a8b-5176-ab39-66d58a4d544e"

[compat]
ClusterManagers = "0.4"
julia = "1"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Distributed"]
