name = "EasyClusterManagersSlurm"
uuid = "4b0af0f2-a3e4-42c8-afa2-c5af2ee86004"
authors = ["Jishnu Bhattacharya <jishnub@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
